[theme]
base = "light"
primaryColor = "#17685C"
backgroundColor = "#FAFBF8"
secondaryBackgroundColor = "#EDF2EC"
textColor = "#20382F"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
